export interface CatalogGame {
  id: string;
  title: string;
  genre: string;
  year: number;
  popular?: boolean;
  developer?: string;
}

export const HUGE_GAMES_DATABASE: CatalogGame[] = [
  // Najpopularniejsze / Top Picks
  { id: 'gta5', title: 'Grand Theft Auto V (GTA 5)', genre: 'Akcja / Otwarty Świat', year: 2013, popular: true, developer: 'Rockstar Games' },
  { id: 'gta6', title: 'Grand Theft Auto VI (GTA 6)', genre: 'Akcja / Otwarty Świat', year: 2025, popular: true, developer: 'Rockstar Games' },
  { id: 'gta4', title: 'Grand Theft Auto IV: The Complete Edition', genre: 'Akcja', year: 2008, developer: 'Rockstar Games' },
  { id: 'gta_sa', title: 'Grand Theft Auto: San Andreas - Definitive Edition', genre: 'Akcja', year: 2021, developer: 'Rockstar Games' },
  { id: 'witcher3', title: 'Wiedźmin 3: Dziki Gon (The Witcher 3: Wild Hunt - Next-Gen)', genre: 'RPG', year: 2015, popular: true, developer: 'CD Projekt RED' },
  { id: 'witcher2', title: 'Wiedźmin 2: Zabójcy Królów', genre: 'RPG', year: 2011, developer: 'CD Projekt RED' },
  { id: 'witcher1', title: 'Wiedźmin 1: Edycja Rozszerzona', genre: 'RPG', year: 2007, developer: 'CD Projekt RED' },
  { id: 'cyberpunk2077', title: 'Cyberpunk 2077: Phantom Liberty', genre: 'RPG / Akcja', year: 2023, popular: true, developer: 'CD Projekt RED' },
  { id: 'eldenring', title: 'Elden Ring: Shadow of the Erdtree', genre: 'Soulslike / RPG', year: 2024, popular: true, developer: 'FromSoftware' },
  { id: 'gow_ragnarok', title: 'God of War Ragnarök', genre: 'Akcja / Przygodowa', year: 2024, popular: true, developer: 'Santa Monica Studio' },
  { id: 'gow_2018', title: 'God of War (2018)', genre: 'Akcja', year: 2018, popular: true, developer: 'Santa Monica Studio' },
  { id: 'rdr2', title: 'Red Dead Redemption 2', genre: 'Akcja / Otwarty Świat', year: 2018, popular: true, developer: 'Rockstar Games' },
  { id: 'rdr1', title: 'Red Dead Redemption (PC)', genre: 'Akcja / Western', year: 2024, popular: true, developer: 'Rockstar Games' },
  { id: 'bg3', title: "Baldur's Gate 3", genre: 'cRPG', year: 2023, popular: true, developer: 'Larian Studios' },
  { id: 'wukong', title: 'Black Myth: Wukong', genre: 'Akcja RPG', year: 2024, popular: true, developer: 'Game Science' },

  // Akcja & Strzelanki
  { id: 'cod_mw3', title: 'Call of Duty: Modern Warfare III (2023)', genre: 'FPS', year: 2023, developer: 'Sledgehammer Games' },
  { id: 'cod_bo6', title: 'Call of Duty: Black Ops 6', genre: 'FPS', year: 2024, popular: true, developer: 'Treyarch' },
  { id: 'cod_mw2', title: 'Call of Duty: Modern Warfare II (2022)', genre: 'FPS', year: 2022, developer: 'Infinity Ward' },
  { id: 'cod_bo2', title: 'Call of Duty: Black Ops II', genre: 'FPS', year: 2012, developer: 'Treyarch' },
  { id: 'bf2042', title: 'Battlefield 2042', genre: 'FPS', year: 2021, developer: 'DICE' },
  { id: 'bf1', title: 'Battlefield 1: Revolution', genre: 'FPS', year: 2016, developer: 'DICE' },
  { id: 'bf5', title: 'Battlefield V: Definitive Edition', genre: 'FPS', year: 2018, developer: 'DICE' },
  { id: 'doom_eternal', title: 'DOOM Eternal: The Ancient Gods', genre: 'FPS / Akcja', year: 2020, developer: 'id Software' },
  { id: 'doom_darkages', title: 'DOOM: The Dark Ages', genre: 'FPS', year: 2025, developer: 'id Software' },
  { id: 'far_cry_6', title: 'Far Cry 6: Game of the Year Edition', genre: 'FPS / Otwarty Świat', year: 2021, developer: 'Ubisoft' },
  { id: 'far_cry_5', title: 'Far Cry 5: Gold Edition', genre: 'FPS', year: 2018, developer: 'Ubisoft' },
  { id: 'far_cry_3', title: 'Far Cry 3: Classic Edition', genre: 'FPS', year: 2012, developer: 'Ubisoft' },
  { id: 'mafia_de', title: 'Mafia: Definitive Edition', genre: 'Akcja', year: 2020, developer: 'Hangar 13' },
  { id: 'mafia_2_de', title: 'Mafia II: Definitive Edition', genre: 'Akcja', year: 2020, developer: '2K Czech' },
  { id: 'mafia_old_country', title: 'Mafia: The Old Country', genre: 'Akcja', year: 2025, developer: 'Hangar 13' },
  { id: 'max_payne_3', title: 'Max Payne 3: The Complete Edition', genre: 'Strzelanka TPP', year: 2012, developer: 'Rockstar Games' },
  { id: 'spiderman_remastered', title: "Marvel's Spider-Man Remastered", genre: 'Akcja', year: 2022, popular: true, developer: 'Insomniac Games' },
  { id: 'spiderman_miles', title: "Marvel's Spider-Man: Miles Morales", genre: 'Akcja', year: 2022, developer: 'Insomniac Games' },
  { id: 'spiderman_2', title: "Marvel's Spider-Man 2", genre: 'Akcja', year: 2024, popular: true, developer: 'Insomniac Games' },
  { id: 'wolverine', title: "Marvel's Wolverine", genre: 'Akcja', year: 2025, developer: 'Insomniac Games' },
  { id: 'helldivers2', title: 'Helldivers 2: Super Citizen Edition', genre: 'Kooperacja / Strzelanka', year: 2024, popular: true, developer: 'Arrowhead' },
  { id: 'ghost_of_tsushima', title: "Ghost of Tsushima: Director's Cut", genre: 'Akcja / Otwarty Świat', year: 2024, popular: true, developer: 'Sucker Punch' },
  { id: 'horizon_fw', title: 'Horizon Forbidden West: Complete Edition', genre: 'Akcja / RPG', year: 2024, developer: 'Guerrilla Games' },
  { id: 'horizon_zd', title: 'Horizon Zero Dawn: Remastered', genre: 'Akcja / RPG', year: 2024, developer: 'Guerrilla Games' },
  { id: 'tlou_part1', title: 'The Last of Us Part I (PC)', genre: 'Przetrwanie / Akcja', year: 2023, popular: true, developer: 'Naughty Dog' },
  { id: 'tlou_part2', title: 'The Last of Us Part II Remastered', genre: 'Przetrwanie / Akcja', year: 2024, developer: 'Naughty Dog' },
  { id: 'uncharted_lot', title: 'UNCHARTED: Legacy of Thieves Collection', genre: 'Przygodowa / Akcja', year: 2022, developer: 'Naughty Dog' },
  { id: 'control_ue', title: 'Control: Ultimate Edition', genre: 'Akcja / Sci-Fi', year: 2020, developer: 'Remedy' },
  { id: 'quantum_break', title: 'Quantum Break', genre: 'Akcja', year: 2016, developer: 'Remedy' },

  // Assassin's Creed Seria
  { id: 'ac_shadows', title: "Assassin's Creed Shadows", genre: 'Akcja / RPG', year: 2025, popular: true, developer: 'Ubisoft' },
  { id: 'ac_mirage', title: "Assassin's Creed Mirage", genre: 'Skradanka / Akcja', year: 2023, developer: 'Ubisoft' },
  { id: 'ac_valhalla', title: "Assassin's Creed Valhalla: Complete Edition", genre: 'RPG / Akcja', year: 2020, developer: 'Ubisoft' },
  { id: 'ac_odyssey', title: "Assassin's Creed Odyssey: Ultimate Edition", genre: 'RPG / Akcja', year: 2018, developer: 'Ubisoft' },
  { id: 'ac_origins', title: "Assassin's Creed Origins: Gold Edition", genre: 'RPG / Akcja', year: 2017, developer: 'Ubisoft' },
  { id: 'ac_blackflag', title: "Assassin's Creed IV: Black Flag", genre: 'Akcja', year: 2013, developer: 'Ubisoft' },

  // RPG / Soulslike / Fantasy
  { id: 'skyrim_ae', title: 'The Elder Scrolls V: Skyrim - Anniversary Edition', genre: 'RPG', year: 2021, popular: true, developer: 'Bethesda' },
  { id: 'oblivion', title: 'The Elder Scrolls IV: Oblivion GOTY', genre: 'RPG', year: 2006, developer: 'Bethesda' },
  { id: 'fallout_4_goty', title: 'Fallout 4: Game of the Year Edition (Next-Gen)', genre: 'RPG / Postapo', year: 2024, popular: true, developer: 'Bethesda' },
  { id: 'fallout_nv', title: 'Fallout: New Vegas Ultimate Edition', genre: 'RPG', year: 2010, developer: 'Obsidian' },
  { id: 'starfield', title: 'Starfield: Shattered Space', genre: 'RPG / Sci-Fi', year: 2024, developer: 'Bethesda' },
  { id: 'hogwarts_legacy', title: 'Hogwarts Legacy: Digital Deluxe Edition', genre: 'Akcja / RPG', year: 2023, popular: true, developer: 'Avalanche Software' },
  { id: 'dragons_dogma_2', title: "Dragon's Dogma 2", genre: 'RPG', year: 2024, developer: 'Capcom' },
  { id: 'monster_hunter_wilds', title: 'Monster Hunter Wilds', genre: 'Akcja RPG', year: 2025, developer: 'Capcom' },
  { id: 'monster_hunter_world', title: 'Monster Hunter: World - Iceborne', genre: 'Akcja RPG', year: 2018, developer: 'Capcom' },
  { id: 'dark_souls_3', title: 'Dark Souls III: The Ringed City', genre: 'Soulslike', year: 2016, popular: true, developer: 'FromSoftware' },
  { id: 'dark_souls_remastered', title: 'Dark Souls: Remastered', genre: 'Soulslike', year: 2018, developer: 'FromSoftware' },
  { id: 'sekiro', title: 'Sekiro: Shadows Die Twice - GOTY Edition', genre: 'Soulslike / Akcja', year: 2019, popular: true, developer: 'FromSoftware' },
  { id: 'lies_of_p', title: 'Lies of P: Deluxe Edition', genre: 'Soulslike', year: 2023, developer: 'NEOWIZ' },
  { id: 'lords_of_fallen', title: 'Lords of the Fallen (2023)', genre: 'Soulslike', year: 2023, developer: 'HEXWORKS' },
  { id: 'stalker_2', title: 'S.T.A.L.K.E.R. 2: Heart of Chornobyl', genre: 'FPS / Survival Horror', year: 2024, popular: true, developer: 'GSC Game World' },
  { id: 'metro_exodus_ee', title: 'Metro Exodus Enhanced Edition', genre: 'FPS / Postapo', year: 2021, developer: '4A Games' },
  { id: 'mass_effect_le', title: 'Mass Effect Legendary Edition', genre: 'RPG / Sci-Fi', year: 2021, developer: 'BioWare' },
  { id: 'dragon_age_veilguard', title: 'Dragon Age: The Veilguard', genre: 'RPG', year: 2024, developer: 'BioWare' },
  { id: 'kingdom_come_2', title: 'Kingdom Come: Deliverance II', genre: 'RPG / Realizm', year: 2025, popular: true, developer: 'Warhorse Studios' },
  { id: 'kingdom_come_1', title: 'Kingdom Come: Deliverance - Royal Edition', genre: 'RPG', year: 2018, developer: 'Warhorse Studios' },
  { id: 'final_fantasy_16', title: 'Final Fantasy XVI (PC Edition)', genre: 'JRPG / Akcja', year: 2024, developer: 'Square Enix' },
  { id: 'final_fantasy_7_rebirth', title: 'Final Fantasy VII Rebirth', genre: 'JRPG', year: 2024, developer: 'Square Enix' },

  // Horrory & Survival
  { id: 're4_remake', title: 'Resident Evil 4 Remake: Gold Edition', genre: 'Survival Horror', year: 2023, popular: true, developer: 'Capcom' },
  { id: 're2_remake', title: 'Resident Evil 2 Remake', genre: 'Survival Horror', year: 2019, developer: 'Capcom' },
  { id: 're_village', title: 'Resident Evil Village: Gold Edition', genre: 'Survival Horror', year: 2021, developer: 'Capcom' },
  { id: 're7_biohazard', title: 'Resident Evil 7: Biohazard', genre: 'Survival Horror', year: 2017, developer: 'Capcom' },
  { id: 'silent_hill_2', title: 'Silent Hill 2 Remake', genre: 'Psychological Horror', year: 2024, popular: true, developer: 'Bloober Team' },
  { id: 'alan_wake_2', title: 'Alan Wake 2: Deluxe Edition + DLCs', genre: 'Survival Horror', year: 2023, popular: true, developer: 'Remedy Entertainment' },
  { id: 'dead_space_remake', title: 'Dead Space Remake (2023)', genre: 'Sci-Fi Horror', year: 2023, developer: 'Motive Studio' },
  { id: 'sons_of_forest', title: 'Sons of the Forest', genre: 'Survival / Horror', year: 2024, popular: true, developer: 'Endnight Games' },
  { id: 'the_forest', title: 'The Forest', genre: 'Survival', year: 2018, developer: 'Endnight Games' },
  { id: 'subnautica', title: 'Subnautica', genre: 'Survival / Underwater', year: 2018, developer: 'Unknown Worlds' },
  { id: 'rust', title: 'Rust: Console & PC Edition', genre: 'Survival Multiplayer', year: 2018, developer: 'Facepunch' },
  { id: 'dayz', title: 'DayZ: Frostline Edition', genre: 'Survival / Zombie', year: 2024, developer: 'Bohemia Interactive' },
  { id: 'dying_light_2', title: 'Dying Light 2: Stay Human - Reloaded', genre: 'Akcja / Zombie / Parkour', year: 2022, developer: 'Techland' },
  { id: 'dead_island_2', title: 'Dead Island 2: Ultimate Edition', genre: 'Akcja / Zombie', year: 2024, developer: 'Dambuster Studios' },

  // Wyścigi & Sportowe
  { id: 'forza_horizon_5', title: 'Forza Horizon 5: Premium Edition', genre: 'Wyścigi / Otwarty Świat', year: 2021, popular: true, developer: 'Playground Games' },
  { id: 'forza_horizon_4', title: 'Forza Horizon 4: Ultimate Edition', genre: 'Wyścigi', year: 2018, developer: 'Playground Games' },
  { id: 'forza_motorsport', title: 'Forza Motorsport (2023)', genre: 'Symulator Wyścigowy', year: 2023, developer: 'Turn 10' },
  { id: 'ea_fc_25', title: 'EA SPORTS FC 25: Ultimate Edition', genre: 'Sport / Piłka Nożna', year: 2024, popular: true, developer: 'EA Sports' },
  { id: 'ea_fc_24', title: 'EA SPORTS FC 24', genre: 'Sport / Piłka Nożna', year: 2023, popular: true, developer: 'EA Sports' },
  { id: 'fifa_23', title: 'FIFA 23: Ultimate Edition', genre: 'Sport', year: 2022, developer: 'EA Sports' },
  { id: 'nba_2k25', title: 'NBA 2K25: All-Star Edition', genre: 'Sport / Koszykówka', year: 2024, developer: 'Visual Concepts' },
  { id: 'nfs_unbound', title: 'Need for Speed Unbound: Palace Edition', genre: 'Wyścigi', year: 2022, developer: 'Criterion Games' },
  { id: 'nfs_heat', title: 'Need for Speed Heat: Deluxe Edition', genre: 'Wyścigi', year: 2019, developer: 'Ghost Games' },
  { id: 'assetto_corsa_evo', title: 'Assetto Corsa EVO', genre: 'Symulator Wyścigowy', year: 2024, developer: 'Kunos Simulazioni' },
  { id: 'f1_24', title: 'F1 24: Champions Edition', genre: 'Wyścigi Formuła 1', year: 2024, developer: 'Codemasters' },
  { id: 'the_crew_motorfest', title: 'The Crew Motorfest: Gold Edition', genre: 'Wyścigi', year: 2023, developer: 'Ubisoft Ivory Tower' },

  // Strategie & Symulatory & Budowanie
  { id: 'manor_lords', title: 'Manor Lords (Early Access)', genre: 'Strategia / Średniowiecze', year: 2024, popular: true, developer: 'Slavic Magic' },
  { id: 'frostpunk_2', title: 'Frostpunk 2: Deluxe Edition', genre: 'Strategia / Survival', year: 2024, popular: true, developer: '11 bit studios' },
  { id: 'civ_7', title: "Sid Meier's Civilization VII", genre: 'Strategia 4X', year: 2025, popular: true, developer: 'Firaxis Games' },
  { id: 'civ_6', title: "Sid Meier's Civilization VI: Anthology", genre: 'Strategia 4X', year: 2016, developer: 'Firaxis Games' },
  { id: 'cities_skylines_2', title: 'Cities: Skylines II', genre: 'Symulator Miasta', year: 2023, developer: 'Colossal Order' },
  { id: 'ets_2', title: 'Euro Truck Simulator 2: Iberia & West Balkans', genre: 'Symulator Ciężarówki', year: 2012, popular: true, developer: 'SCS Software' },
  { id: 'fs_25', title: 'Farming Simulator 25: Collector Edition', genre: 'Symulator Rolnictwa', year: 2024, popular: true, developer: 'GIANTS Software' },
  { id: 'fs_22', title: 'Farming Simulator 22: Platinum Edition', genre: 'Symulator', year: 2021, developer: 'GIANTS Software' },
  { id: 'msfs_2024', title: 'Microsoft Flight Simulator 2024', genre: 'Symulator Lotu', year: 2024, popular: true, developer: 'Asobo Studio' },
  { id: 'age_of_empires_4', title: 'Age of Empires IV: Anniversary Edition', genre: 'RTS', year: 2021, developer: 'Relic / World\'s Edge' },
  { id: 'hearts_of_iron_4', title: 'Hearts of Iron IV: Ultimate Bundle', genre: 'Grand Strategy', year: 2016, developer: 'Paradox' },
  { id: 'stellaris', title: 'Stellaris: Ultimate Bundle', genre: 'Kosmiczna Strategia', year: 2016, developer: 'Paradox' },
  { id: 'crusader_kings_3', title: 'Crusader Kings III: Royal Edition', genre: 'Strategia / RPG', year: 2020, developer: 'Paradox' },
  { id: 'total_war_wh3', title: 'Total War: WARHAMMER III', genre: 'Strategia', year: 2022, developer: 'Creative Assembly' },

  // Sandbox, Niezależne i Inne Klasyki
  { id: 'minecraft', title: 'Minecraft: Java & Bedrock Edition', genre: 'Sandbox / Przygoda', year: 2011, popular: true, developer: 'Mojang Studios' },
  { id: 'palworld', title: 'Palworld', genre: 'Survival / Stworki', year: 2024, popular: true, developer: 'Pocketpair' },
  { id: 'terraria', title: 'Terraria (Latest Version)', genre: 'Sandbox 2D', year: 2011, developer: 'Re-Logic' },
  { id: 'valheim', title: 'Valheim: Ashlands Update', genre: 'Survival / Wikingowie', year: 2021, developer: 'Iron Gate' },
  { id: 'hades_2', title: 'Hades II (Early Access)', genre: 'Roguelike / Akcja', year: 2024, popular: true, developer: 'Supergiant Games' },
  { id: 'hades_1', title: 'Hades', genre: 'Roguelike', year: 2020, developer: 'Supergiant Games' },
  { id: 'hollow_knight_silksong', title: 'Hollow Knight: Silksong', genre: 'Metroidvania', year: 2025, developer: 'Team Cherry' },
  { id: 'hollow_knight', title: 'Hollow Knight: Voidheart Edition', genre: 'Metroidvania', year: 2017, developer: 'Team Cherry' },
  { id: 'stardew_valley', title: 'Stardew Valley (v1.6 Update)', genre: 'RPG / Farma', year: 2016, developer: 'ConcernedApe' },
  { id: 'teardown', title: 'Teardown: Ultimate Edition', genre: 'Fizyka / Demolka', year: 2022, developer: 'Tuxedo Labs' },
  { id: 'beamng_drive', title: 'BeamNG.drive', genre: 'Symulator Fizyki Pojazdów', year: 2015, popular: true, developer: 'BeamNG' },
  { id: 'the_sims_4', title: 'The Sims 4: Wszystkie Dodatki (All DLCs Pack)', genre: 'Symulator Życia', year: 2014, popular: true, developer: 'Maxis' },
  { id: 'stellar_blade', title: 'Stellar Blade (PC Edition)', genre: 'Akcja / Sci-Fi', year: 2025, developer: 'Shift Up' },
  { id: 'arma_reforger', title: 'Arma Reforger / Arma 4', genre: 'Milsim', year: 2022, developer: 'Bohemia Interactive' },
  { id: 'squad', title: 'Squad', genre: 'Taktyczny Milsim', year: 2020, developer: 'Offworld Industries' },
  { id: 'escape_from_tarkov', title: 'Escape from Tarkov (SP-Tarkov Offline)', genre: 'Ekstrakcyjna Strzelanka', year: 2020, developer: 'Battlestate Games' },
];
